server:
  port: 8080
  servlet:
    context-path: /heart
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sswh?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**